[Xdebug]
zend_extension=xdebug
xdebug.mode=debug,coverage
xdebug.idekey=PHPSESSID
xdebug.profiler_output_name = "cachegrind.out.%p"
xdebug.log_level = 10
xdebug.profiler_append = 0
xdebug.use_compression = true
xdebug.start_with_request = yes
#port and host set in docker-compose.yml
